services:
  
  api:
    build: 
      context: ./server
      dockerfile: Dockerfile

    container_name: draacuna-api

    working_dir: /app
    
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env.docker
    

    restart: unless-stopped