services:
  frontend:
      env_file:
        - ./.env.development

      command: npm run dev -- --host 0.0.0.0
  api:
    env_file:
      - ./server/.env.dev
    depends_on:
      postgres:
        condition: service_healthy

  postgres:

    environment:
      POSTGRES_USER: dra_acuna
      POSTGRES_PASSWORD: acuna123
      POSTGRES_DB: dra_acuna_dev

    ports:
      - "5433:5432"

    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dra_acuna -d dra_acuna_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_dev: