services:
  
  api:
    build: 
      context: ./server
      dockerfile: Dockerfile

    

    working_dir: /app
    
    ports:
      - "3000:3000"
     

    restart: unless-stopped
  postgres:
    image: postgres:17
    restart: unless-stopped